"""create stock_reports and analysis_jobs tables

Revision ID: d730c3884ddb
Revises: 
Create Date: 2026-03-23 15:07:54.508939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd730c3884ddb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_job_id'), 'analysis_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_analysis_jobs_ticker'), 'analysis_jobs', ['ticker'], unique=False)
    op.create_table('stock_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('fundamental_score', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('technical_score', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('weighted_score', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('recommendation', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_reports_ticker'), 'stock_reports', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_reports_ticker'), table_name='stock_reports')
    op.drop_table('stock_reports')
    op.drop_index(op.f('ix_analysis_jobs_ticker'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_job_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
